### ISSUE TITLE
border and border-radius sorting error

### ISSUE THREAD

**Issue by albertorestifo** [atom/sort-lines#22]
I can only reproduce this error using the proprieties `border` and `border-radius`. Take the following CSS:

```css
.some-element {
  border-radius: 1em;
  border: 1px solid #000;
}
```

Applying the sorting does not affect the order.
