### ISSUE TITLE
Sorting css doesn't sort properly

### ISSUE THREAD

**Issue by themoonisacheese** [atom/sort-lines#87]
### Description

Since this morning, sorting CSS lines results in some lines being sorted out of expected order.

### Steps to Reproduce

1. Have a rule such as:
 ```css
h1{
    font-variant: small-caps;
    text-align: center;
    font-weight: normal;
    color: #E16A72; /* rose */
}
```
2. Select the content of the rule and press F5

**Expected behavior:** i should end up with 
```css
h1{
    color: #E16A72; /* rose */
    font-variant: small-caps;
    font-weight: normal;
    text-align: center;
}
```

**Actual behavior:** I instead end up with:
```css
h1{
    text-align: center;
    color: #E16A72; /* rose */
    font-variant: small-caps;
    font-weight: normal;
}
```

**Reproduces how often:** If it decides this particular group won't be sorted properly, 100% of the time.
Most groups sort fine.

### Versions

Atom    : 1.19.6
Electron: 1.6.9
Chrome  : 56.0.2924.87
Node    : 7.4.0

apm  1.18.4
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.14.2

Running linux 4.9.0-4-amd64 on KDE/MATE

### Additional Information

I do not appear to have any other packages that can modify text.
